name: Run Python Script

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Change this to your Python version if necessary

    - name: Install dependencies
      run: |
        pip install pytube

    - name: Run script
      run: python YouTube2.py
